### ISSUE TITLE
drawing error in CirclePageIndicator

### ISSUE THREAD

**Issue by larshesel** [JakeWharton/ViewPagerIndicator#13]
Hi

just pulled the 965055da8aba49d8d6d66306b4995b14ab47ff3d changeset from the master branch.

When using the circlepageindicator, it seems to work if I the circle indicator goes from the left to the right (when flipping/dragging a page). Going back it seems to be drawing the left destination indicator-circle first, then draws the intermediate indicator-circles.

This behavior is visible in both direction when clicking left or right of the indicator.

I don't have the great overview of how the code should work, but If I apply the diff blow, that behavior goes away. The mCurrentPage also seem to be set correctly after the page has been scrolled/swipe, even if it is not set as per the patch below. 

Cheers,
Lars

The auto formatting screwed up the diff I had pasted, so I instead committed it to my own fork:

https://github.com/larshesel/Android-ViewPagerIndicator/commit/c371b888dc41e9fa8dc00247d9c005479c9d370f

**Comment by JakeWharton** [comment]
I've read this a few times and played with the sample app on my phone and in the emulator and fail to see any problem with the rendering.

You are correct that the circles which represent each page are drawn first (from left to right) and then the selection dot is drawn last.

Can you describe what exactly the rendering error is more clearly so I know exactly what to look for? Perhaps I need to add some sleep calls to slow down rendering a bit to make it more evident.

**Comment by SimonVT** [comment]
The issue is onPageScrolled and onPageSelected reporting different positions.

onPageScrolled will always get the left-most visible page as position, while onPageSelected gets the destination page.

If you scroll from page 0 to page 1, onPageScrolled will invalidate the view with position = 0. If you let go of the screen during the scroll (to let ViewPager autoscroll the rest), onPageSelected will invalidate the view with position = 1 the moment you let go, after which onPageScrolled will invalidate the view with position = 0 for the remainder for the scroll.

When pressing the indicator, onPageSelected will be called with position being the target page, while onPageScrolled is called for the remainder of the scroll with position being the left-most visible page.

It's not visible in the sample app, probably because the Fragments are very simple.

I suspect this is also the reason for not acting on onPageSelected in TitlePagerAdapter (issue #11).

**Comment by JakeWharton** [comment]
Would it be possible to supply an obvious test case? Even if it's something as stupid as blocking the UI thread for 500ms on every call to `draw()` or making stupid slow fragments in the pager.

Real life is very busy the next 6+ weeks and the upcoming ICS release and inevitable r4 compat lib is going to gravitate 95% of my free programming time to ActionBarSherlock. Sorry guys.

**Comment by SimonVT** [comment]
I'll provide a test case later today, when I get home from work.

**Comment by larshesel** [comment]
Hi Jake

I'll try to dig up an example that is reproducible. I'm sorry that I didn't get back earlier, but real life is getting in the way.

Cheers,
Lars

**Comment by JakeWharton** [comment]
919f8a95a5787aaa83c992edfca28f9f7f094567
