### ISSUE TITLE
Give Superclass chance to handle Touch Events

### ISSUE THREAD

**Issue by chrisbanes** [JakeWharton/ViewPagerIndicator#45]
I would send a Pull Request for this but I've made another commit previously which you will not want ([this one](https://github.com/chrisbanes/Android-ViewPagerIndicator/commit/f6e172ce390468874d6ee92e180227f9dfa66769)).

At the moment, TitlePageIndicator and CirclePageIndicator gobble up all Touch Events at the end, where as they should send them up to the superclass. That way, any click listeners will have a chance to work.

Here's my commit on my fork: https://github.com/chrisbanes/Android-ViewPagerIndicator/commit/6e43f79eccc55ff3ff2644986e478b2404366ff0

**Comment by JakeWharton** [comment]
This seems to steal _all_ touch events.

**Comment by JakeWharton** [comment]
Shouldn't it be:

``` java
if (super.onTouchEvent(event)) {
    return true;
}
```

at the start of each method?

**Comment by rfgamaral** [comment]
I've taken a look at this, that doesn't work either @JakeWharton.

Because that `if` will always be true and the `onTouchEvent` method will exit. So clicking on a title won't move to that page :/

I tried to fix it, but was unable to. I don't know how to make both the superclass handle events without stealing all the others.
