### ISSUE TITLE
TabPageIndicator doesn't work with any styles but Widget.TabPageIndicator

### ISSUE THREAD

**Issue by brk3** [JakeWharton/ViewPagerIndicator#66]
On the latest revision (f09acb0) simply changing 

android:theme="@style/Theme.PageIndicatorDefaults" 

to,

android:theme="@android:style/Theme.Light"

completely breaks any of the samples that use TabPageIndicator.  This makes it unusable with ActionBarSherlock or any app that wants to use some custom theming.

Screenshot of the problem: http://imgur.com/wMlCC

The contents of Theme.PageIndicatorDefaults seems quite minimal, so it can be worked around by adding these lines to your own theme that extends Theme.Sherlock, or whatever else.  This is likely the same problem as what was been described in issue #38.

**Comment by JakeWharton** [comment]
TabPageIndicator only works with themes because it's View-based rather than
Canvas-based. As this library progresses the regular title indicator will
move toward this as well.

The default theme only has about three or four attributes in it which just
point to built in styles. To use with other libraries that have style
requirements you just need to copy the one or two attributes into your own
theme. You don't need your own styles for the indicator, just the theme
attributes for the defaults. There's no other easy way around it because of
how Android styles work.

I hope that most people are customizing the look of the indicators for
their own apps anyways which would necessitate doing this anyway. The
GitHub Gaug.es app is a good example of using ABS and VPI together with
extremely simple styling that gives a nice branding.
On Mar 1, 2012 5:22 AM, "Paul Bourke" <
reply@reply.github.com>
wrote:

**Comment by brk3** [comment]
Makes sense, thanks for the concise explanation!
